[settings]
idiomatic_version_file_enable_tools = ["pnpm", "yarn", "npm", "node"]
minimum_release_age = "0"

[tools]
java = "lts"
ni = "latest"
node = "lts"
opencode = "latest"
pi = "latest"
pnpm = "latest"
vercel = { version = "latest", allow_builds = ["esbuild"], trust_policy_excludes = ["undici"] }
yarn = "latest"
